### ISSUE TITLE
50 Char Password Limit

### ISSUE THREAD

**Issue by imreallyliam** [Neztore/save-server#2]
A simple thing, there's just a 50 character password limit.

**Comment by Neztore** [comment]
I'll probably either:
- Make it customisable
- Make the limit longer

Though for the short term 50 characters is **very** secure anyway, but I can see why you'd want this to be customisable.

**Comment by Neztore** [comment]
Note: Increasing the limit dramatically may not actually help much.

> Per bcrypt implementation, only the first 72 bytes of a string are used. Any extra bytes are ignored when matching passwords. Note that this is not the first 72 characters. It is possible for a string to contain less than 72 characters, while taking up more than 72 bytes (e.g. a UTF-8 encoded string containing emojis).

[Bcrypt](https://www.npmjs.com/package/bcrypt#security-issues-and-concerns) only uses the first 72 bytes.
