### ISSUE TITLE
CSRF token validation error

### ISSUE THREAD

**Issue by jxpsert** [Neztore/save-server#20]
Hi there! This error occurs when attempting to delete an image from iOS Safari.
![image](https://user-images.githubusercontent.com/65042215/103586893-5dea1a80-4ee6-11eb-8f05-afb918132b9d.jpeg)

I've attempted logging in again, yielding no results. So far, I haven't had this issue on desktop.

Some helpful information;
- saveserver 1.2.0
- running on node 12.18.3
- server on Ubuntu 18.04

- iOS 14.2
- iPhone 7

Same issue both using 4G and WiFi.

**Comment by ReduxGB** [comment]
What browser were you using when you received the error?

**Comment by jxpsert** [comment]
Magically, after switching from dashboard to home and back (I’ve tried this before) it worked. Not sure what happened there, but it's functional.

**Comment by jxpsert** [comment]
> What browser were you using when you received the error?

As the original issue says, Safari on iOS.

**Comment by Neztore** [comment]
Can't reproduce: CSRF tokens are issued correctly as far as I can tell.
