### ISSUE TITLE
Incorrect upload time

### ISSUE THREAD

**Issue by jxpsert** [Neztore/save-server#24]
**Describe the bug**
When clicking on a recently (<1 minute ago) uploaded image, the text under it says it was uploaded 2 hours ago.

**To Reproduce**
1. Upload an image
2. Enter the dashboard
3. Click on the image you just uploaded
4. Text states username and "2 hours ago"

**Expected behavior**
Text under image says "just now" / whatever time ago it was actually uploaded

**Screenshots**
![thing](https://i.jxpr.eu/22baaa.png)

**Additional context**
 - Browser: Firefox 88.0

I think this may be caused by something timezone-y. My server's timezone is set to CEST, which I'm also in, so this should be correct.

**Comment by ReduxGB** [comment]
Can I ask what timezone you are in? Might have found the issue but need to check if I'm correct.

**Comment by jxpsert** [comment]
I'm in CEST (GMT+2).

**Comment by Neztore** [comment]
Javascript and the date-time format we use (ISO 8601) support timezones by default.
I suspect this is SQLite doing something funky and discarding timezones or similar.

**Comment by Neztore** [comment]
Won't fix: low priority
