### ISSUE TITLE
Server throws in production when running without Cloudflare

### ISSUE THREAD

**Issue by EirikFA** [Neztore/save-server#32]
Server throws <a href="https://github.com/Neztore/save-server/blob/master/server/middleware/ratelimit.js#L76">here</a> when running with `NODE_ENV` set to `production` and not using Cloudflare, effectively making Cloudflare mandatory.

**To Reproduce**
1. Start the project with `NODE_ENV` set to `production`: `NODE_ENV=production npm start` (on Linux)
2. Try to access the server, will see a 500 "No Cloudflare IP available"

**Expected behavior**
Project works without using Cloudflare.

Can probably be fixed by changing <a href="https://github.com/Neztore/save-server/blob/master/server/middleware/ratelimit.js#L73-L81">this snippet</a> to
```js
const ip = req.get("CF-Connecting-IP");
if (!ip) {
  return req.ip;
}
```

This will support Cloudflare but fall back instead of throwing an error in production. Alternatively, to only support Cloudflare in production, one could do
```js
const ip = req.get("CF-Connecting-IP");
if (!ip || NODE_ENV !== "production") {
  return req.ip;
}
```

**Comment by Neztore** [comment]
Fixed in #34
