### ISSUE TITLE
Reset root password

### ISSUE THREAD

**Issue by kaziu687** [Neztore/save-server#37]
Sometimes (in my case today) root password need to be reset without removing other users. Is there a way to reset it to defaults (for example env variable)?

**Comment by Neztore** [comment]
There is not at present. This could be achieved by opening the SQlite file in a suitable application and replacing the password hash for root with a valid bcrypt hash of the desired password (or with the original hash from the provided SQlite DB)

**Comment by Neztore** [comment]
Going to follow up and close this with: I'm hesitant to add this sort of capability as it means it's fairly trivial if someone gets access to your server (or to the save-server instance in some way) for them to trigger a password reset for the root. Please refer to the above manual steps.
