### ISSUE TITLE
Issue Deleting User

### ISSUE THREAD

**Issue by imreallyliam** [Neztore/save-server#7]
When deleting a user and content then recreating a user, ghosts of the past uploads exist.

**Comment by Neztore** [comment]
Hi, what do you mean "Ghost"?
Is this if you use the "Delete user and all content" button?
"Delete user" deletes the user and moves their images to root.
"Delete user and all content" deletes the user and removes that user's uploads entirely.

**Comment by imreallyliam** [comment]
If I use the "Delete user and all content", when remaking an account with the same username, those uploads can be "seen" but don't actually exist. You can open them and click the URL but it is a 404. My guess is that the button doesn't remove the entries from the database.

**Comment by Neztore** [comment]
Ah. If I remember correctly this was meant to happen with a cascade in the Database - I'll have a look today or tomorrow and get this sorted.
Thanks for reporting!

**Comment by Neztore** [comment]
I've looked into this.
Not sure why; When using DB Browser the cascade works as expected. But not using our driver.
Could be something pragma related but at present I'm going to fix it by adding a delete statement.
Fix out shortly!
